### Verbo GET – listar
GET http://localhost:8000/funcionario/ HTTP/1.1
x-token: abcBolinhasToken
x-key: abcBolinhasKey

### Verbo GET – listar todos
curl -X 'GET' \
    'http://localhost:8000/funcionario/' \
    -H 'accept: application/json' \
    -H 'x-token: abcBolinhasToken' \
    -H 'x-key: abcBolinhasKey'

### Verbo POST - adicionar
POST http://localhost:8000/funcionario/ HTTP/1.1
content-type : application/json
x-token: abcBolinhasToken
x-key: abcBolinhasKey

{
    "nome" : "Arthur Michaltchuk",
    "matricula" : "123",
    "cpf" : "1234",
    "telefone" : "49988234567",
    "grupo" : 1,
    "senha" : "cd3333f0c034749ceead5de4d14aff9b1d18f2d4e6f3ac3fc3f81b84b5f8a24b"
}

### Verbo PUT - atualiza
PUT http://127.0.0.1:8000/funcionario/1 HTTP/1.1
content-type : application/json
x-token: abcBolinhasToken
x-key: abcBolinhasKey

{
    "nome" : "José Luiz Fernandes" ,
    "matricula" : "54321" ,
    "cpf" : "12345678909" ,
    "telefone" : "4996526363S" ,
    "grupo" : 2 ,
    "senha" : "abc"
}

### Verbo DELETE - atualiza
DELETE http://127.0.0.1:8000/funcionario/1 HTTP/1.1
content-type : application/json
x-token: abcBolinhasToken
x-key: abcBolinhasKey